AllCops:
  Exclude:
    - db/*
    - bin/*

Documentation:
  Enabled: false

DotPosition:
  EnforcedStyle: trailing

Encoding:
  Enabled: false

HandleExceptions:
  Enabled: false

LineLength:
  Max: 120

NumericLiterals:
  Enabled: false

SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

TrailingBlankLines:
  Enabled: false
